---
# Source: assemble-api-gateway-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: newDemo
  labels:
    app: newDemo
    application: newDemo
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: newDemo
    application: newDemo
